---
# Note: Because this repo started without a linter, we're starting with
# extremely permissive rules. We'll tighten up these rules over time as we
# fix previous linter errors.

# heading-increment/header-increment
MD001: false
# ul-indent
MD007: false
# no-trailing-spaces
MD009: false
# line-length
MD013: false
# no-duplicate-heading/no-duplicate-header
MD024: false
# single-title/single-h1
MD025: false
# no-trailing-punctuation
MD026: false
# ol-prefix
MD029: false
# list-marker-space
MD030: false
# blanks-around-fences
MD031: false
# blanks-around-lists
MD032: false
# no-inline-html
MD033: false
# no-bare-urls
MD034: false
# no-emphasis-as-heading/no-emphasis-as-header
MD036: false
# no-space-in-emphasis
MD037: false
# fenced-code-language
MD040: false
# first-line-heading/first-line-h1
MD041: false
# code-block-style
MD046: false
# single-trailing-newline
MD047: false
