---
# line-length
# Markdown files don't need to observe a line length limit.
MD013: false

# no-duplicate-heading/no-duplicate-header
# It's acceptable to have duplicate headers in the same file sometimes, like
# when multiple sections have a subsection called "### Example".
MD024: false

# no-trailing-punctuation
# Without this rule suppression, the linter flags trailing punctuation in
# headers like "## What makes Gridsome sites fast?" but we allow headers
# like that.
MD026: false

# no-inline-html
MD033:
  # We use inline HTML to embed the Newsletter component in a page.
  allowed_elements:
    - div
    - Newsletter

# no-bare-urls
# The linter flags http://example.com and wants them formatted like
# <http://example.com>, but this doesn't improve readability.
MD034: false

# Note: Because this repo started without a linter, the rules below are
# suppressed for compatibility with legacy code, but we should either fix the
# linter errors and remove the exceptions or explicitly choose to ignore the
# rule permanently and move it to the list above with an explanation of why we
# ignore the rule.

# heading-increment/header-increment
MD001: false
# ul-indent
MD007: false
# single-title/single-h1
MD025: false
# ol-prefix
MD029: false
# list-marker-space
MD030: false
# blanks-around-fences
MD031: false
# blanks-around-lists
MD032: false
# no-emphasis-as-heading/no-emphasis-as-header
MD036: false
# no-space-in-emphasis
MD037: false
# first-line-heading/first-line-h1
MD041: false
