---
# line-length
# Markdown files don't need to observe a line length limit.
MD013: false

# no-duplicate-heading/no-duplicate-header
# It's acceptable to have duplicate headers in the same file sometimes, like
# when multiple sections have a subsection called "### Example".
MD024: false

# no-trailing-punctuation
# Without this rule suppression, the linter flags trailing punctuation in
# headers like "## What makes Gridsome sites fast?" but we allow headers
# like that.
MD026: false

# no-inline-html
MD033:
  # We use inline HTML to embed the Newsletter component in a page.
  allowed_elements:
    - div
    - Newsletter

# no-bare-urls
# The linter flags http://example.com and wants them formatted like
# <http://example.com>, but this doesn't improve readability.
MD034: false

# heading-increment/header-increment
# As there are often multiple sections in a page, they don't always sequentially decrement,
# so we allow this
MD001: false

# ol-prefix
# Some lists are seperated by multiple lines (for example code blocks in-between)
MD029: false

# no-emphasis-as-heading/no-emphasis-as-header
# Sometimes an emphasis is used inbetween sections, but not actually as a header - so we allow this.
MD036: false
